### PR TITLE
Add archiver app faq

### PR DESCRIPTION
**Pull request by titaniumbones**
first run at an FAQ for the archiver app, mostly drawn from the SF Bay
event.  needs work!

### CODE REVIEW

**Comment by dcwalk** [comment]
Going to close this and re-open, as it looks like it started on the `master` branch but probably should go on `gh-pages`

**Comment by titaniumbones** [comment]
argh, sorry. am really too tired to be pushing commits.

**Comment by dcwalk** [comment]
No worries, just doing a copy-edit and will get a new PR up

**Comment by titaniumbones** [comment]
feel free to ninja-merge & alert @b5 in case he has time to link to it from the app -- I'm going to bed, gotta get some rest.

**Pull request closed without merging**
